[pytest]
testpaths = app/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# Added -p no:warnings to silence the internal package deprecations
addopts = -v -p no:warnings
asyncio_mode = auto